library(reticulate)
library(Seurat)
library(anndata)
use_python("/home/xi/anaconda3/bin/python")
py_run_string("print('Hello World from python')")
anndata <- import("anndata")
seurat <- readRDS("cells_1207.Rdata")
counts <- GetAssayData(seurat,assay = "RNA")
counts <- as.matrix(counts)
feature <- as.character(rownames(counts))
barcode <- as.character(colnames(counts))
barcode <- paste0("Cell_",barcode)
adata <- anndata::AnnData(X = t(counts),obs = barcode,var = feature)

anndata::write_h5ad(adata,"/home/xi/Desktop/R/cells_1207.h5ad")
