---
title: "Plate_Plot_All"
author: "Xi Luo"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(ggplot2)
library(reshape2)
library(Seurat)
library(dplyr)
library(pheatmap)
library(ramify)
library(readxl)
library(Polychrome)
library(ggplate)


embryo_data_list=c("1-1","1-3","2-2","3-1","3-2","6-1","6-2","6-3")
data_list = list()
for (n in 1:8){
  data_list[[n]]=Read10X(data.dir = paste0("/home/xi/Desktop/2024-5-8-human_embryo/human_1101/",embryo_data_list[n]))
  print(n)
}

nUMI_list =list()
for(n in 1:8){
  nUMI_list[[n]] = Matrix::colSums(data_list[[n]])
  print(n)
}

hist_list = list()
for(n in 1:8){
  hist_list[[n]] = hist(log10(nUMI_list[[n]]),main=paste('counts per cell',paste0("plate 1 ",embryo_data_list[[n]])),col='burlywood1'
       ,xlim = range(0:6),ylim = range(0:20),breaks = 40)
}

white_list_check <- read_excel("white_list_for_scRNA.xlsx",col_names = FALSE)
ordered_wl = flatten(as.matrix(white_list_check), across = c("rows", "columns"))


plateplot <- function(test1,num){
  a <- Matrix::colSums(test1)
  a <- data.frame(a)
  a$barcode <- rownames(a)
  a <- a[ordered_wl,]
  AtoH <- c('A','B','C','D','E','F','G','H')
  a$well <- paste0(rep(AtoH,each = 12),rep((c(1:12)) , time = 8))
  a$Value <- log10(a$a +1)
  plate_plot(data = a,plate_size = 96,value = Value,position = well,plate_type = "round",title = paste0("plate " , num))
}

for(n in 1:8){
  print(plateplot(data_list[[n]],embryo_data_list[n]))
}

```



```{r}

library(ggplot2)
library(reshape2)
library(Seurat)
library(dplyr)
library(pheatmap)
library(ramify)
library(readxl)
library(Polychrome)
library(ggplate)

embryo_data_list=c("1-1","1-2","1-3","1-4","1-5","2-1","2-2","3-1","4-1","4-2","4-3","5-2","6")
data_list = list()
for (n in 1:13){
  data_list[[n]]=Read10X(data.dir = paste0("/home/xi/Desktop/2024-5-8-human_embryo/human_1207/",embryo_data_list[n]))
  print(n)
}



nUMI_list =list()
for(n in 1:13){
  nUMI_list[[n]] = Matrix::colSums(data_list[[n]])
  print(n)
}

hist_list = list()
for(n in 1:13){
  hist_list[[n]] = hist(log10(nUMI_list[[n]]),main=paste('counts per cell',paste0("plate 2 ",embryo_data_list[[n]])),col='burlywood1'
       ,xlim = range(0:6),ylim = range(0:20),breaks = 40)
}

white_list_check <- read_excel("white_list_for_scRNA.xlsx",col_names = FALSE)
ordered_wl = flatten(as.matrix(white_list_check), across = c("rows", "columns"))


plateplot <- function(test1,num){
  a <- Matrix::colSums(test1)
  a <- data.frame(a)
  a$barcode <- rownames(a)
  a <- a[ordered_wl,]
  AtoH <- c('A','B','C','D','E','F','G','H')
  a$well <- paste0(rep(AtoH,each = 12),rep((c(1:12)) , time = 8))
  a$Value <- log10(a$a +1)
  plate_plot(data = a,plate_size = 96,value = Value,position = well,plate_type = "round",title = paste0("plate " , num))
}

for(n in 1:13){
  print(plateplot(data_list[[n]],embryo_data_list[n]))
}

```



```{r}
library(ggplot2)
library(reshape2)
library(Seurat)
library(dplyr)
library(pheatmap)
library(ramify)
library(readxl)
library(Polychrome)
library(ggplate)


embryo_data_list=c("3-1_1","3-1_2","3-1_3","3-1_4","3-2_1","3-2_2","3-2_3","3-2_4","3-2_5","3-3_1","3-3_2","3-3_3","3-3_4","3-5_1_E10_2-6","3-6_1","3-6_2","3-6_3","3-7_1")
data_list = list()
for (n in 1:18){
  data_list[[n]]=Read10X(data.dir = paste0("/home/xi/Desktop/human_embryo_scs_20230112/",embryo_data_list[n]))
  print(n)
}

#histograms for each plate
nUMI_list =list()
for(n in 1:18){
  nUMI_list[[n]] = Matrix::colSums(data_list[[n]])
  print(n)
}

hist_list = list()
for(n in 1:18){
  hist_list[[n]] = hist(log10(nUMI_list[[n]]),main=paste('counts per cell',paste0("plate ",embryo_data_list[[n]])),col="#a1caf1"
                        ,xlim = range(0:6),ylim = range(0:30),breaks = 50)
}


white_list_check <- read_excel("white_list_check.xlsx",col_names = FALSE)
ordered_wl = flatten(as.matrix(white_list_check), across = c("rows", "columns"))


plateplot <- function(test1,num){
  a <- Matrix::colSums(test1)
  a <- data.frame(a)
  a$barcode <- rownames(a)
  a <- a[ordered_wl,]
  AtoH <- c('A','B','C','D','E','F','G','H')
  a$well <- paste0(rep(AtoH,each = 12),rep((c(1:12)) , time = 8))
  a$Value <- log10(a$a +1)
  plate_plot(data = a,plate_size = 96,value = Value,position = well,plate_type = "round",title = paste0("plate " , num))
}

for(n in 1:18){
  print(plateplot(data_list[[n]],embryo_data_list[n]))
}
  a <- Matrix::colSums(data_list[[4]])
  a <- data.frame(a)
  a$barcode <- rownames(a)
  a <- a[ordered_wl,]
  AtoH <- c('A','B','C','D','E','F','G','H')
  a$well <- paste0(rep(AtoH,each = 12),rep((c(1:12)) , time = 8))
  a$Value <- log10(a$a +1)
  plate_plot(data = a,plate_size = 96,value = Value,position = well,plate_type = "round",title = paste0("plate " , "1"))
a$Value
a
```